[build]
  functions = "netlify/functions"
  publish = "dist" # or your frontend build folder (e.g., "build" for React)

[[redirects]]
  from = "/feedbacks"
  to = "/.netlify/functions/feedbacks"
  status = 200
